// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(geocoordinates_ffiFFI)
import geocoordinates_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_geocoordinates_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_geocoordinates_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureGeocoordinatesFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


/**
 * An **approximate** GCJ-02 position — the FFI-flattened form of
 * `Approx<Gcj02>`. `max_error_m` is the estimated upper bound on positional
 * error, in meters.
 */
public struct ApproxGcj02: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double
    /**
     * Estimated maximum positional error, in meters.
     */
    public var maxErrorM: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double, 
        /**
         * Estimated maximum positional error, in meters.
         */maxErrorM: Double) {
        self.lat = lat
        self.lon = lon
        self.maxErrorM = maxErrorM
    }

    

    
}

#if compiler(>=6)
extension ApproxGcj02: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApproxGcj02: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApproxGcj02 {
        return
            try ApproxGcj02(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf), 
                maxErrorM: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: ApproxGcj02, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
        FfiConverterDouble.write(value.maxErrorM, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApproxGcj02_lift(_ buf: RustBuffer) throws -> ApproxGcj02 {
    return try FfiConverterTypeApproxGcj02.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApproxGcj02_lower(_ value: ApproxGcj02) -> RustBuffer {
    return FfiConverterTypeApproxGcj02.lower(value)
}


/**
 * An **approximate** WGS-84 position — the FFI-flattened form of
 * `Approx<Wgs84>`. `max_error_m` is the estimated upper bound on positional
 * error, in meters.
 */
public struct ApproxWgs84: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double
    /**
     * Estimated maximum positional error, in meters.
     */
    public var maxErrorM: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double, 
        /**
         * Estimated maximum positional error, in meters.
         */maxErrorM: Double) {
        self.lat = lat
        self.lon = lon
        self.maxErrorM = maxErrorM
    }

    

    
}

#if compiler(>=6)
extension ApproxWgs84: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApproxWgs84: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApproxWgs84 {
        return
            try ApproxWgs84(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf), 
                maxErrorM: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: ApproxWgs84, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
        FfiConverterDouble.write(value.maxErrorM, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApproxWgs84_lift(_ buf: RustBuffer) throws -> ApproxWgs84 {
    return try FfiConverterTypeApproxWgs84.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApproxWgs84_lower(_ value: ApproxWgs84) -> RustBuffer {
    return FfiConverterTypeApproxWgs84.lower(value)
}


/**
 * A Baidu Web Mercator position, in projected meters.
 */
public struct BaiduMercator: Equatable, Hashable {
    /**
     * Easting (longitude axis), in meters.
     */
    public var x: Double
    /**
     * Northing (latitude axis), in meters.
     */
    public var y: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Easting (longitude axis), in meters.
         */x: Double, 
        /**
         * Northing (latitude axis), in meters.
         */y: Double) {
        self.x = x
        self.y = y
    }

    

    
}

#if compiler(>=6)
extension BaiduMercator: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBaiduMercator: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BaiduMercator {
        return
            try BaiduMercator(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: BaiduMercator, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBaiduMercator_lift(_ buf: RustBuffer) throws -> BaiduMercator {
    return try FfiConverterTypeBaiduMercator.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBaiduMercator_lower(_ value: BaiduMercator) -> RustBuffer {
    return FfiConverterTypeBaiduMercator.lower(value)
}


/**
 * A BD-09 position (Baidu Maps only), in decimal degrees.
 */
public struct Bd09: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double) {
        self.lat = lat
        self.lon = lon
    }

    

    
}

#if compiler(>=6)
extension Bd09: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBd09: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bd09 {
        return
            try Bd09(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Bd09, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBd09_lift(_ buf: RustBuffer) throws -> Bd09 {
    return try FfiConverterTypeBd09.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBd09_lower(_ value: Bd09) -> RustBuffer {
    return FfiConverterTypeBd09.lower(value)
}


/**
 * The canonical coordinate — mirror of [`gc::Coordinate`].
 */
public struct Coordinate: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double
    /**
     * Optional height (ellipsoidal or orthometric).
     */
    public var height: Height?
    /**
     * The reference system the position is expressed in.
     */
    public var crs: Crs

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double, 
        /**
         * Optional height (ellipsoidal or orthometric).
         */height: Height?, 
        /**
         * The reference system the position is expressed in.
         */crs: Crs) {
        self.lat = lat
        self.lon = lon
        self.height = height
        self.crs = crs
    }

    

    
}

#if compiler(>=6)
extension Coordinate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoordinate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Coordinate {
        return
            try Coordinate(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf), 
                height: FfiConverterOptionTypeHeight.read(from: &buf), 
                crs: FfiConverterTypeCrs.read(from: &buf)
        )
    }

    public static func write(_ value: Coordinate, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
        FfiConverterOptionTypeHeight.write(value.height, into: &buf)
        FfiConverterTypeCrs.write(value.crs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinate_lift(_ buf: RustBuffer) throws -> Coordinate {
    return try FfiConverterTypeCoordinate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoordinate_lower(_ value: Coordinate) -> RustBuffer {
    return FfiConverterTypeCoordinate.lower(value)
}


/**
 * A GCJ-02 position (Google China, AutoNavi/高德, Tencent), in decimal degrees.
 */
public struct Gcj02: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double) {
        self.lat = lat
        self.lon = lon
    }

    

    
}

#if compiler(>=6)
extension Gcj02: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGcj02: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Gcj02 {
        return
            try Gcj02(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Gcj02, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGcj02_lift(_ buf: RustBuffer) throws -> Gcj02 {
    return try FfiConverterTypeGcj02.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGcj02_lower(_ value: Gcj02) -> RustBuffer {
    return FfiConverterTypeGcj02.lower(value)
}


/**
 * A WGS-84 position (real GPS / OpenStreetMap), in decimal degrees.
 */
public struct Wgs84: Equatable, Hashable {
    /**
     * Latitude in decimal degrees.
     */
    public var lat: Double
    /**
     * Longitude in decimal degrees.
     */
    public var lon: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Latitude in decimal degrees.
         */lat: Double, 
        /**
         * Longitude in decimal degrees.
         */lon: Double) {
        self.lat = lat
        self.lon = lon
    }

    

    
}

#if compiler(>=6)
extension Wgs84: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWgs84: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Wgs84 {
        return
            try Wgs84(
                lat: FfiConverterDouble.read(from: &buf), 
                lon: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Wgs84, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.lat, into: &buf)
        FfiConverterDouble.write(value.lon, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWgs84_lift(_ buf: RustBuffer) throws -> Wgs84 {
    return try FfiConverterTypeWgs84.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWgs84_lower(_ value: Wgs84) -> RustBuffer {
    return FfiConverterTypeWgs84.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Coordinate reference system / datum tag — mirror of [`gc::Crs`].
 *
 * A closed snapshot of the upstream `#[non_exhaustive]` enum. A variant added
 * upstream must be mirrored here too (see `AGENTS.md`).
 */

public enum Crs: Equatable, Hashable {
    
    /**
     * WGS-84 — the global GNSS reference and library default.
     */
    case wgs84
    /**
     * GCJ-02 — "Mars" coordinates used by Chinese map providers.
     */
    case gcj02
    /**
     * BD-09 — Baidu's additional obfuscation atop GCJ-02.
     */
    case bd09
    /**
     * NAD27 — North American Datum 1927.
     */
    case nad27
    /**
     * Tokyo datum (legacy Japan / Korea).
     */
    case tokyo
    /**
     * Pulkovo-1942 / SK-42.
     */
    case pulkovo42





}

#if compiler(>=6)
extension Crs: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCrs: FfiConverterRustBuffer {
    typealias SwiftType = Crs

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Crs {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .wgs84
        
        case 2: return .gcj02
        
        case 3: return .bd09
        
        case 4: return .nad27
        
        case 5: return .tokyo
        
        case 6: return .pulkovo42
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Crs, into buf: inout [UInt8]) {
        switch value {
        
        
        case .wgs84:
            writeInt(&buf, Int32(1))
        
        
        case .gcj02:
            writeInt(&buf, Int32(2))
        
        
        case .bd09:
            writeInt(&buf, Int32(3))
        
        
        case .nad27:
            writeInt(&buf, Int32(4))
        
        
        case .tokyo:
            writeInt(&buf, Int32(5))
        
        
        case .pulkovo42:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrs_lift(_ buf: RustBuffer) throws -> Crs {
    return try FfiConverterTypeCrs.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCrs_lower(_ value: Crs) -> RustBuffer {
    return FfiConverterTypeCrs.lower(value)
}



/**
 * Errors surfaced across the FFI boundary — a flattened mirror of [`gc::Error`].
 *
 * Datum-bearing variants carry their reference systems as their canonical
 * short names (e.g. `"BD-09"`); everything else collapses into [`GeoError::Other`].
 */
public enum GeoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * A coordinate carried the wrong reference system for the requested operation.
     */
    case CrsMismatch(
        /**
         * The reference system that was required.
         */expected: String, 
        /**
         * The reference system the coordinate actually carried.
         */found: String
    )
    /**
     * A latitude/longitude fell outside its valid domain.
     */
    case OutOfRange(
        /**
         * Offending latitude in degrees.
         */lat: Double, 
        /**
         * Offending longitude in degrees.
         */lon: Double
    )
    /**
     * Any other library error, with its message preserved.
     */
    case Other(
        /**
         * The underlying error's display message.
         */message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension GeoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGeoError: FfiConverterRustBuffer {
    typealias SwiftType = GeoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GeoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .CrsMismatch(
            expected: try FfiConverterString.read(from: &buf), 
            found: try FfiConverterString.read(from: &buf)
            )
        case 2: return .OutOfRange(
            lat: try FfiConverterDouble.read(from: &buf), 
            lon: try FfiConverterDouble.read(from: &buf)
            )
        case 3: return .Other(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: GeoError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .CrsMismatch(expected,found):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(expected, into: &buf)
            FfiConverterString.write(found, into: &buf)
            
        
        case let .OutOfRange(lat,lon):
            writeInt(&buf, Int32(2))
            FfiConverterDouble.write(lat, into: &buf)
            FfiConverterDouble.write(lon, into: &buf)
            
        
        case let .Other(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoError_lift(_ buf: RustBuffer) throws -> GeoError {
    return try FfiConverterTypeGeoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGeoError_lower(_ value: GeoError) -> RustBuffer {
    return FfiConverterTypeGeoError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A height value tagged by its reference surface — mirror of [`gc::Height`].
 */

public enum Height: Equatable, Hashable {
    
    /**
     * Meters above the reference ellipsoid.
     */
    case ellipsoidal(
        /**
         * Height in meters.
         */meters: Double
    )
    /**
     * Meters above the geoid (mean sea level).
     */
    case orthometric(
        /**
         * Height in meters.
         */meters: Double
    )





}

#if compiler(>=6)
extension Height: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeight: FfiConverterRustBuffer {
    typealias SwiftType = Height

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Height {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .ellipsoidal(meters: try FfiConverterDouble.read(from: &buf)
        )
        
        case 2: return .orthometric(meters: try FfiConverterDouble.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Height, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .ellipsoidal(meters):
            writeInt(&buf, Int32(1))
            FfiConverterDouble.write(meters, into: &buf)
            
        
        case let .orthometric(meters):
            writeInt(&buf, Int32(2))
            FfiConverterDouble.write(meters, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeight_lift(_ buf: RustBuffer) throws -> Height {
    return try FfiConverterTypeHeight.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeight_lower(_ value: Height) -> RustBuffer {
    return FfiConverterTypeHeight.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeight: FfiConverterRustBuffer {
    typealias SwiftType = Height?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeight.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeight.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * BD-09 lat/lon → Baidu Web Mercator (exact forward projection).
 */
public func baiduMercatorFromBd09(p: Bd09) -> BaiduMercator  {
    return try!  FfiConverterTypeBaiduMercator_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_baidu_mercator_from_bd09(
        FfiConverterTypeBd09_lower(p),$0
    )
})
}
/**
 * Baidu Web Mercator → BD-09 lat/lon (exact inverse projection).
 */
public func baiduMercatorToBd09(m: BaiduMercator) -> Bd09  {
    return try!  FfiConverterTypeBd09_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_baidu_mercator_to_bd09(
        FfiConverterTypeBaiduMercator_lower(m),$0
    )
})
}
/**
 * Baidu Web Mercator → canonical [`Coordinate`], tagged BD-09 (exact).
 */
public func baiduMercatorToCoordinate(m: BaiduMercator) -> Coordinate  {
    return try!  FfiConverterTypeCoordinate_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_baidu_mercator_to_coordinate(
        FfiConverterTypeBaiduMercator_lower(m),$0
    )
})
}
/**
 * Canonical [`Coordinate`] → Baidu Web Mercator.
 *
 * Errors with [`GeoError::CrsMismatch`] unless the coordinate is BD-09 — a
 * non-BD-09 coordinate must be converted to BD-09 first, never silently
 * reprojected.
 */
public func baiduMercatorTryFromCoordinate(coord: Coordinate)throws  -> BaiduMercator  {
    return try  FfiConverterTypeBaiduMercator_lift(try rustCallWithError(FfiConverterTypeGeoError_lift) {
    uniffi_geocoordinates_ffi_fn_func_baidu_mercator_try_from_coordinate(
        FfiConverterTypeCoordinate_lower(coord),$0
    )
})
}
/**
 * BD-09 → GCJ-02, fast single-step inverse. **Approximate**: the returned
 * record carries `max_error_m`.
 */
public func bd09ToGcj02Fast(p: Bd09) -> ApproxGcj02  {
    return try!  FfiConverterTypeApproxGcj02_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_bd09_to_gcj02_fast(
        FfiConverterTypeBd09_lower(p),$0
    )
})
}
/**
 * BD-09 → GCJ-02, refined fixed-point inverse (sub-meter). **Approximate**:
 * the returned record carries `max_error_m`.
 */
public func bd09ToGcj02Refined(p: Bd09) -> ApproxGcj02  {
    return try!  FfiConverterTypeApproxGcj02_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_bd09_to_gcj02_refined(
        FfiConverterTypeBd09_lower(p),$0
    )
})
}
/**
 * BD-09 → WGS-84, refined composition through GCJ-02. **Approximate**: the
 * returned record carries the summed `max_error_m`.
 */
public func bd09ToWgs84Refined(p: Bd09) -> ApproxWgs84  {
    return try!  FfiConverterTypeApproxWgs84_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_bd09_to_wgs84_refined(
        FfiConverterTypeBd09_lower(p),$0
    )
})
}
/**
 * Construct a BD-09 [`Coordinate`] from latitude/longitude in degrees.
 */
public func coordinateBd09(lat: Double, lon: Double) -> Coordinate  {
    return try!  FfiConverterTypeCoordinate_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_coordinate_bd09(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lon),$0
    )
})
}
/**
 * Construct a GCJ-02 [`Coordinate`] from latitude/longitude in degrees.
 */
public func coordinateGcj02(lat: Double, lon: Double) -> Coordinate  {
    return try!  FfiConverterTypeCoordinate_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_coordinate_gcj02(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lon),$0
    )
})
}
/**
 * Construct a WGS-84 [`Coordinate`] from latitude/longitude in degrees.
 */
public func coordinateWgs84(lat: Double, lon: Double) -> Coordinate  {
    return try!  FfiConverterTypeCoordinate_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_coordinate_wgs84(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lon),$0
    )
})
}
/**
 * GCJ-02 → BD-09. **Exact** forward nudge.
 */
public func gcj02ToBd09(p: Gcj02) -> Bd09  {
    return try!  FfiConverterTypeBd09_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_gcj02_to_bd09(
        FfiConverterTypeGcj02_lower(p),$0
    )
})
}
/**
 * GCJ-02 → WGS-84, fast single-step inverse (~1–2 m). **Approximate**: the
 * returned record carries `max_error_m`.
 */
public func gcj02ToWgs84Fast(p: Gcj02) -> ApproxWgs84  {
    return try!  FfiConverterTypeApproxWgs84_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_gcj02_to_wgs84_fast(
        FfiConverterTypeGcj02_lower(p),$0
    )
})
}
/**
 * GCJ-02 → WGS-84, refined fixed-point inverse (< 0.5 m). **Approximate**: the
 * returned record carries `max_error_m`.
 */
public func gcj02ToWgs84Refined(p: Gcj02) -> ApproxWgs84  {
    return try!  FfiConverterTypeApproxWgs84_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_gcj02_to_wgs84_refined(
        FfiConverterTypeGcj02_lower(p),$0
    )
})
}
/**
 * Cheap spherical (haversine) distance between two coordinates, in **meters**.
 *
 * `Length` and its operators do not cross the FFI boundary, so the scalar
 * meters value is returned directly.
 */
public func haversineDistanceM(a: Coordinate, b: Coordinate) -> Double  {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_haversine_distance_m(
        FfiConverterTypeCoordinate_lower(a),
        FfiConverterTypeCoordinate_lower(b),$0
    )
})
}
/**
 * Whether `(lat, lon)` lies outside the China bounding box, where every China
 * datum conversion is the identity.
 */
public func outOfChina(lat: Double, lon: Double) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_out_of_china(
        FfiConverterDouble.lower(lat),
        FfiConverterDouble.lower(lon),$0
    )
})
}
/**
 * WGS-84 → BD-09. **Exact** composition through GCJ-02.
 */
public func wgs84ToBd09(p: Wgs84) -> Bd09  {
    return try!  FfiConverterTypeBd09_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_wgs84_to_bd09(
        FfiConverterTypeWgs84_lower(p),$0
    )
})
}
/**
 * WGS-84 → GCJ-02. **Exact** forward offset (identity outside China).
 */
public func wgs84ToGcj02(p: Wgs84) -> Gcj02  {
    return try!  FfiConverterTypeGcj02_lift(try! rustCall() {
    uniffi_geocoordinates_ffi_fn_func_wgs84_to_gcj02(
        FfiConverterTypeWgs84_lower(p),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_geocoordinates_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_baidu_mercator_from_bd09() != 56758) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_baidu_mercator_to_bd09() != 24966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_baidu_mercator_to_coordinate() != 37386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_baidu_mercator_try_from_coordinate() != 8208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_bd09_to_gcj02_fast() != 22966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_bd09_to_gcj02_refined() != 22650) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_bd09_to_wgs84_refined() != 56707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_coordinate_bd09() != 48845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_coordinate_gcj02() != 23936) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_coordinate_wgs84() != 5480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_gcj02_to_bd09() != 50524) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_gcj02_to_wgs84_fast() != 31114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_gcj02_to_wgs84_refined() != 60232) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_haversine_distance_m() != 19983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_out_of_china() != 22213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_wgs84_to_bd09() != 50018) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_geocoordinates_ffi_checksum_func_wgs84_to_gcj02() != 48908) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureGeocoordinatesFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all